platform :ios, '8.0'

target 'baisiAPP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for baisiAPP
  pod 'SDWebImage','3.7.5'
  pod 'AFNetworking', '2.5.4'
  pod 'MJExtension', '2.0.4'
end
