platform :ios, '8.0'

target 'baisiAPP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for baisiAPP
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.10'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'SVProgressHUD', '~> 2.0.3'
  pod 'DACircularProgress', '~> 2.3.1'
end
